dist: xenial
language: node_js
node_js:
  - "8"
  - "9"
  - "10"
cache: yarn
before_install:
  - sudo apt-get install libsecret-1-dev dbus gnome-keyring python-keyring python-gnomekeyring
before_script:
  - sudo chmod 0711 /usr/bin/gnome-keyring-daemon
  - sudo chmod u-s /usr/bin/gnome-keyring-daemon
  - ls -l /usr/bin/gnome-keyring-daemon
  - eval $(echo -n "" | /usr/bin/gnome-keyring-daemon --login)
  - eval $(/usr/bin/gnome-keyring-daemon --components=secrets --start)
  - dbus-launch /usr/bin/python -c "import gnomekeyring;gnomekeyring.create_sync('login', '');"
script:
  - yarn test
  - cd examples/example-subgraph
  - yarn
  - ../../graph.js codegen --output-dir src/types --debug
  - ../../graph.js build --debug
  # - echo 'auth optional pam_gnome_keyring.so' | sudo tee -a /etc/pam.d/login
  # - echo 'session optional pam_gnome_keyring.so auto_start' | sudo tee -a /etc/pam.d/login
  # - echo 'eval $(dbus-launch /usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh); export $(dbus-launch gnome-keyring-daemon --start --components=pkcs11,secrets,ssh,gpg)' >> ~/.xinitrc
  - ps ax
  - dbus-launch bash -c 'GNOME_KEYRING_CONTROL=1 ../../graph.js auth http://some-node-ip.org test-access-token'
