language: node_js
node_js:
  - "8"
  - "9"
  - "10"
cache: yarn
before_install:
  - sudo apt-get install libsecret-1-dev dbus
script:
  - yarn test
  - cd examples/example-subgraph
  - yarn
  - ../../graph.js codegen --output-dir src/types --debug
  - ../../graph.js build --debug
  - dbus-run-session ../../graph.js auth http://some-node-ip.org test-access-token
